FROM centos:centos7
RUN yum -y update && yum -y install httpd && yum -y install httpd-tools && yum -y install php && yum -y install php-mysql && yum -y install php-gd && yum -y install php-xml 
WORKDIR /opt/apps
RUN wget https://releases.wikimedia.org/mediawiki/1.34/mediawiki-1.34.2.tar.gz 
RUN wget https://releases.wikimedia.org/mediawiki/1.34/mediawiki-1.34.2.tar.gz.sig && gpg --verify mediawiki-1.34.2.tar.gz.sig mediawiki-1.34.2.tar.gz
RUN tar -zxf /home/username/mediawiki-1.34.2.tar.gz 
RUN cd /var/www && ln -s /opt/apps/mediawiki-1.34.2/ mediawiki
RUN chown -R apache:apache /var/www/mediawiki
RUN sed -i -e 's/DocumentRoot "/var/www/html"/DocumentRoot "/var/www"/' /etc/httpd/conf/httpd.conf
RUN sed -i -e 's/<Directory "/var/www/html">"/<Directory "/var/www">/' /etc/httpd/conf/httpd.conf
EXPOSE 80 
CMD [“service”, “httpd”,“start”]
