FROM centos:centos7
ENV  MYSQL_VERSION=5.5 \
     HOME=/var/lib/mysql
EXPOSE 3306 //MySQL Container will listen on this PORT
RUN yum install -y centos-release-scl && \
    INSTALL_PKGS="tar rsync gettext hostname bind-utils mysql55" && \
    yum -y --setopt=tsflags=nodocs install $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    yum -y clean all --enablerepo='*' && \
    mkdir -p /var/lib/mysql/data && chown -R mysql.0 /var/lib/mysql && \
    test "$(id mysql)" = "uid=27(mysql) gid=27(mysql) groups=27(mysql)"
ENV CONTAINER_SCRIPTS_PATH=/usr/share/container-scripts/mysql \
    MYSQL_PREFIX=/opt/rh/mysql55/root/usr \
    ENABLED_COLLECTIONS=mysql55
ENV BASH_ENV=${CONTAINER_SCRIPTS_PATH}/scl_enable \
    ENV=${CONTAINER_SCRIPTS_PATH}/scl_enable \
    PROMPT_COMMAND=". ${CONTAINER_SCRIPTS_PATH}/scl_enable"
RUN /usr/libexec/container-setup
VOLUME ["/var/lib/mysql/data"] //Data Volume Must be Persist 
ENTRYPOINT ["container-entrypoint"]
CMD ["run-mysqld"] // Passing the Argument in ENTRYPOINT To run mysal Database 

