---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: mediawiki-pvc
   annotations:
     volume.beta.kubernetes.io/storage-class: px-ha-sc
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 100Gi  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-wiki-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  mediawiki
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
      - name: mediawiki
        image: mediawiki:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
         volumeMounts:
        - mountPath: /var/www
          name: mediawiki-data
      imagePullSecret:
      -	name: secret-registry
      volumes:
      - name: mediawiki-data
        persistentVolumeClaim:
          claimName: mediawiki-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: mediawiki-service
  spec:
    selector:
      app: mediawiki
    type: LoadBalancer
    ports:
    - Port: 80
      targetport: 80 
      protocol: TCP

