apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-wiki-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  mediawiki
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
      - name: mediawiki
        image: sudipkumar5/mediawik-app
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80