---
apiVersion: v1
kind: Secret
metadata:
  name: mysqldb-secret
data:
  NAME : MYSQL_ROOT_PASSWORD
  VALUE:  <encrypted_password>

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: my-mysql-pvc
   annotations:
     volume.beta.kubernetes.io/storage-class: px-ha-sc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi  
	  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mysql  
  template:
    metadata:
      labels:
        db: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.5
        imagePullPolicy: "Always"
        envFrom:
        - secretRef:
            name: mysqldb-secret       
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql/data
          name: mysql-data
      imagePullSecret:
      -	name: secret-registry
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: my-mysql-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: my-sql-service
spec:
  selector:
    db: mysql
  type: ClusterIP
  ports:
  -	Port: 3306
    targetport: 3306 
    protocol: TCP
