apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mysql  
  template:
    metadata:
      labels:
        db: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.5.58
        imagePullPolicy: "Always"
        envFrom:
        - secretRef:
            name: mysqlsecrets       
        ports:
        - containerPort: 3306